### PR TITLE
Add NSCA support

### PR DESCRIPTION
**Pull request by killgufo**
To solve issue #83 and #55 I added NSCA support to the container.
If the configuration file for nsca is not specified there no impact, so people with a running setup can transparently update to this version of the container.

### CODE REVIEW

**Comment by killgufo** [comment]
@JasonRivers did you have time to check my PR?

**Comment by killgufo** [comment]
@JasonRivers do you plan on accepting PR on your project? I am running with NSCA without problems since a couple of months, FWIW.

**Comment by JasonRivers** [comment]
Hi @killgufo Sorry for the long delay here, there's been a lot happening.
Is it possible to have the config stored in /opt/ This may require building it from source in the same way we do with other nagios packages. The last commit to NSCA ~2 years ago, is it still supported by Nagios?

**Comment by rogerniesten** [comment]
Just a side note related to this topic...

I also had the need for handling of passive checks in Nagios. When browsing through nagios docs and forums, I came to the conclusion that NRDP ([Nagios Remote Data Processor](https://exchange.nagios.org/directory/Addons/Passive-Checks/NRDP--2D-Nagios-Remote-Data-Processor/details)) is a more powerful, more flexible and more secure alternative for NSCA. So I went for NRDP.

In my dockerfile (based on jasonrivers/nagios:4.4.2) I use NRDP without any issues for several months now for passive checks (and I'm also planning to use it for executing external commands)

The relevant part in my dockerfile is:
```
ENV NRDP_REPO=https://github.com/NagiosEnterprises/nrdp
ENV NRDP_VERSION=1.5.2

# install nrdp plugin for passive checks & external commands

RUN cd /tmp/ && \
    wget ${NRDP_REPO}/archive/${NRDP_VERSION}.tar.gz && \
    tar xvf ${NRDP_VERSION}.tar.gz && \
    cd nrdp-${NRDP_VERSION} && \
    mkdir /usr/local/nrdp && \
    cp -r clients server LICENSE* CHANGES* /usr/local/nrdp && \
    chown -R nagios:nagios /usr/local/nrdp && \
    cp /tmp/nrdp-${NRDP_VERSION}/nrdp.conf /etc/apache2/sites-available/ && \
    ln -s /etc/apache2/sites-available/nrdp.conf /etc/apache2/sites-enabled/nrdp.conf && \
    rm -rf /tmp/nrdp-* && \
    apt-get update && \
    apt-get -y install php-xml

# Add config file for NRDP
ADD ./nrdp-config.inc.php /usr/local/nrdp/server/config.inc.php

```


More information about NRDP: 
https://assets.nagios.com/downloads/nrdp/docs/NRDP_Overview.pdf?__hstc=118811158.f1e6a4a7455f9e341810aa1bce8c6a2d.1527784323857.1554708343391.1555322541042.35&__hssc=118811158.1.1555322541042&__hsfp=3926253939#_ga=2.243783237.1934666676.1555322541-887659518.1527784324

**Comment by killgufo** [comment]
> Hi @killgufo Sorry for the long delay here, there's been a lot happening.

No worries

> Is it possible to have the config stored in /opt/ This may require building it from source in the same way we do with other nagios packages. The last commit to NSCA ~2 years ago, is it still supported by Nagios?

For what concern it being supported I see it is: https://support.nagios.com/kb/article/nagios-xi-how-to-use-the-nsca-addon-282.html and it worked for me® the past few years, and with your docker container in the past months.

Moving the config to /opt is no issue for me, instead of compiling from source I'd rather just move the file from /etc/nsca.conf in /opt/nsca/nsca.conf and check for the existence of the config file in there instead of where I check now before starting the daemon.
Would that work for you?

**Comment by killgufo** [comment]
Is it now matching what you expected @JasonRivers ?

**Comment by killgufo** [comment]
@JasonRivers Sleeping 10 seconds before starting this daemon makes it work better. Shall I push the patch to this branch or keep it private? What I mean is, are you interested in having this functionality upstream or not?

**Comment by JasonRivers** [comment]
I have added NSCA support in 865731dd;
Sorry for the long delay in adding this in!

**Comment by AsierraDEV** [comment]
It would be useful to add the nsca port to the mappings of the docker command explained in the readme.

Thanks for the work!

**Pull request closed without merging**
