### PR TITLE
fixed hardcoded paths for NAGIOS_HOME

### PR DESCRIPTION
**Pull request by wmoore28**
Just some clean-up to use $NAGIOS_HOME instead of hardcoded paths to /opt/nagios.

### CODE REVIEW

**Comment by JasonRivers** [comment]
Thanks for your contribution, I'll check this out manually as Travis is failing

**Comment by JasonRivers** [comment]
The problem is sourceforge is down - As soon as that's back up (apparently it's been down for hours) I'll get this built (and clone nagiosgraph to github just in case).

**Comment by wmoore28** [comment]
SF was tying me up yesterday because of that. With regards to the MR, the way your overlay/ is setup NAGIOS_HOME can't really be changed without other mods anyways. So it may be irrelevant. But if you do want to accept the MR, start_nagios has hardcoded paths and I didn't updated. 

Anyways, nice work. 

Wesley

**Comment by JasonRivers** [comment]
Thanks for your contribution, I have now taken a copy of nagiosgraph from SF on to my Github, so if SF goes away again I still have access to it!

**Pull request merged**
