### PR TITLE
Replace "/tmp" by $TMPDIR

### PR DESCRIPTION
**Pull request by stonio**

### CODE REVIEW

**Comment by JasonRivers** [comment]
$TMPDIR is not set in the container. Which means this change will put these files in the root of the system.

**Comment by stonio** [comment]
You mean `$TMPDIR` is interpreted as an undeclared `ENV` Docker variable ?

$TMPDIR is a [canonical Unix environment variable](https://en.wikipedia.org/wiki/TMPDIR) available out of the box. Could make your script more robust if `/tmp` does not exist...).

**Comment by shane-axiom** [comment]
`env | grep TMPDIR` returns nothing for me in a Debian Jessie environment (non-Docker).

This image is based on Ubuntu, so `/tmp` should always exist.

**Comment by JasonRivers** [comment]
Indeed, referring to an environment variable that doesn't exist (and therefor writes data to / instead of where you want it) isn't going to work here.

I know /tmp exists, why replace with an environment variable that doesn't? It doesn't make anything more robust if the environment variable doesn't exist.

**Pull request closed without merging**
