### PR TITLE
Nagiosgraph etc & var dirs as Docker volumes

### PR DESCRIPTION
**Pull request by jtome**
Following my suggestion on #41 I propose this change.

### CODE REVIEW

**Comment by JasonRivers** [comment]
Thanks for your contribution, I already had these changes locally, so I have now pushed them to the repository, the next build should have it in.

**Comment by jtome** [comment]
Uhm, in my very first test this is not working. I think that the directories `etc` and `var` of nagiosgraph have to be populated with content the first time you launch the instance, like you are doing for the others directories.

**Comment by JasonRivers** [comment]
This is a valid point, I'll create a new issue for populating them, This may take slightly longer, in the meantime, you can start an image without mounting them and use docker cp to copy the files out. I should have this done in a few days.

**Comment by jtome** [comment]
Thanks again @JasonRivers. Yes, I have started an instance without mounting that directories and copied back to my host the default contents as a workaround.

**Pull request closed without merging**
